### ISSUE TITLE
Curso JavaScript Ninja

### ISSUE THREAD

**Issue by onlurking** [onlurking/sophia#1]
### Aula #01
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Introdução **(11:11)**
- [ ] **2.** Variáveis e tipos de dados **(15:00)**
- [ ] **3.** Operadores aritméticos **(09:35)**
- [ ] **4.** Operadores de igualdade e relacionais **(10:59)**
- [ ] **5.** Funções **(13:31)**
- [ ] **6.** Desafio da semana #01 **(11:38)**
</details>

### Aula #02
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão Desafio da semana #01 **(18:31)**
- [ ] **2.** Operadores Lógicos **(09:20)**
- [ ] **3.** Operadores Unários **(06:25)**
- [ ] **4.** Estrutura Léxica **(13:04)**
- [ ] **5.** Instruções Condicionais - IF **(09:47)**
- [ ] **6.** Desafio da Semana #02 **(14:19)**
</details>

### Aula #03
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana 02 - Parte 1 **(10:51)**
- [ ] **2.** Revisão do desafio da semana 02 - Parte 2 **(11:15)**
- [ ] **3.** Revisão do desafio da semana 02 - Parte 3 **(14:01)**
- [ ] **4.** Tipos de dados e objetos **(11:32)**
- [ ] **5.** Métodos de objeto **(09:56)**
- [ ] **6.** Métodos de objeto (continuação) e desafio da semana #03 **(14:22)**
</details>

### Aula #04
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana 03 - Parte 1 **(15:22)**
- [ ] **2.** Revisão do desafio da semana 03 - Parte 2 **(20:10)**
- [ ] **3.** Truthy e Falsy **(10:01)**
- [ ] **4.** Condicional Ternário **(08:57)**
- [ ] **5.** Escopo de variáveis e funções **(10:25)**
- [ ] **6.** Desafio da semana #04 **(01:23)**
</details>

### Aula #05
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #04 - Parte 1 **(16:32)**
- [ ] **2.** Revisão do desafio da semana #04 - Parte 2 **(16:33)**
- [ ] **3.** Revisão do desafio da semana #04 - Parte 3 **(31:09)**
- [ ] **4.** Retorno de funções com arrays e objetos **(08:37)**
- [ ] **5.** Parâmetros de Funções como arrays e objetos **(08:16)**
- [ ] **6.** Desafio da semana #05 **(10:55)**
</details>

### Aula #06
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão Desafio da semana #05 - Parte 1 **(10:39)**
- [ ] **2.** Revisão Desafio da semana #05 - parte 2 **(10:41)**
- [ ] **3.** Revisão Desafio da semana #05 - parte 3 **(11:25)**
- [ ] **4.** Revisão Desafio da semana #05 - parte 4 **(08:10)**
- [ ] **5.** Operador virgula e estrutura condicional switch **(13:24)**
- [ ] **6.** Estrutura de repetição While e desafio da semana #06 **(09:40)**
</details>

### Aula #07
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #06 - Parte 1 **(11:41)**
- [ ] **2.** Revisão do desafio da semana #06 - Parte 2 **(12:33)**
- [ ] **3.** O operador módulo **(09:06)**
- [ ] **4.** Arrays - a propriedade length **(11:13)**
- [ ] **5.** Arrays - método "push()" e Loop "for" **(09:49)**
- [ ] **6.** Desafio da semana #07 **(03:43)**
</details>

### Aula #08
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão Desafio semana #07 **(20:58)**
- [ ] **2.** A importância de nomear funções **(09:04)**
- [ ] **3.** Introdução à Functional Programming **(10:57)**
- [ ] **4.** Functional Programming - parte 2 **(08:19)**
- [ ] **5.** Functional Programming - parte 3 **(08:59)**
- [ ] **6.** Desafio da semana #08 **(01:13)**
</details>

### Aula #09
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio semana #08 - Parte 1 **(08:34)**
- [ ] **2.** Revisão desafio semana #08 - Parte 2 **(13:15)**
- [ ] **3.** Escopo de funções **(11:45)**
- [ ] **4.** hoisting **(14:31)**
- [ ] **5.** IIFE - Immediately-Invoked Function Expression **(13:09)**
- [ ] **6.** Desafio semana #09 **(02:16)**
</details>

### Aula #10
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio da semana #09 - Parte 1 **(09:44)**
- [ ] **2.** Revisão desafio da semana #09 - Parte 2 **(12:47)**
- [ ] **3.** Revisão desafio da semana #09 - Parte 3 **(10:50)**
- [ ] **4.** Wrapper Objects **(11:19)**
- [ ] **5.** typeof **(14:12)**
- [ ] **6.** Desafio da semana #10 **(01:23)**
</details>

### Aula #11
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio semana #10 - Parte 1 **(10:29)**
- [ ] **2.** Revisão desafio semana #10 - parte 2 **(11:17)**
- [ ] **3.** Errata correção do desafio a semana #10 (próximo vídeo) **(00:29)**
- [ ] **4.** Revisão desafio semana #10 - parte 3 **(20:39)**
- [ ] **5.** Laços (Loops) **(10:44)**
- [ ] **6.** Saltos **(12:39)**
- [ ] **7.** Desafio semana #11 **(01:17)**
</details>

### Aula #12
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio semana #11 - Parte 1 **(11:40)**
- [ ] **2.** Revisão desafio semana #11 - parte 2 **(07:21)**
- [ ] **3.** Criação de objetos **(11:19)**
- [ ] **4.** Criação de objetos - Object.create **(10:41)**
- [ ] **5.** Métodos de objeto **(11:14)**
- [ ] **6.** Arrays - Métodos **(05:13)**
</details>

### Aula #13
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio semana #12 - Parte 1 **(10:43)**
- [ ] **2.** Revisão desafio semana #12 - Parte 2 **(11:49)**
- [ ] **3.** Arrays - toString, concat, unshift e shift **(10:56)**
- [ ] **4.** slice e splice **(11:28)**
- [ ] **5.** forEach, every, some **(08:58)**
- [ ] **6.** map, filter e desafio da semana #13 **(10:48)**
</details>

### Aula #14
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #13 - Parte 1 **(11:44)**
- [ ] **2.** Revisão do desafio da semana #13 - parte 2 **(10:42)**
- [ ] **3.** Revisão do desafio da semana #13 - parte 3 **(18:30)**
- [ ] **4.** reduce() e reduceRight() **(11:30)**
- [ ] **5.** indexOf(), lastIndexOf() e isArray() **(10:36)**
- [ ] **6.** Desafio da semana #14 **(01:01)**
</details>

### Aula #15
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #14 - Parte 1 **(13:07)**
- [ ] **2.** Revisão do desafio da semana #14 - parte 2 **(12:34)**
- [ ] **3.** Revisão do desafio da semana #14 - parte 3 **(14:30)**
- [ ] **4.** JS no browser **(17:37)**
- [ ] **5.** O objeto this **(19:35)**
- [ ] **6.** Objeto arguments e desafio da semana #15 **(05:33)**
</details>

### Aula #16
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio da semana #15 **(18:28)**
- [ ] **2.** use strict - Criação de variáveis sem o "var" **(11:12)**
- [ ] **3.** use strict - uso do with e global this === undefined **(09:46)**
- [ ] **4.** use strict - o operador delete, objetos e funções **(08:13)**
- [ ] **5.** Objeto String **(12:59)**
- [ ] **6.** Objeto String - parte 2 e desafio da semana #16 **(05:24)**
</details>

### Aula #17
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #16 - parte 1 **(13:42)**
- [ ] **2.** Revisão do desafio da semana #16 - parte 2 **(15:42)**
- [ ] **3.** Revisão do desafio da semana #16 - parte 3 **(11:27)**
- [ ] **4.** Regex - Parte 1 **(13:15)**
- [ ] **5.** Regex - parte 2 **(13:59)**
- [ ] **6.** Regex - parte 3 **(16:44)**
</details>

### Aula #18
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio da semana #17 - Parte 1 **(10:44)**
- [ ] **2.** Revisão desafio da semana #17 - parte 2 **(15:58)**
- [ ] **3.** Revisão desafio da semana #17 - parte 3 **(09:31)**
- [ ] **4.** Continuação de Regex **(11:39)**
- [ ] **5.** Regex - Negação **(11:58)**
- [ ] **6.** Regex - Repetidores **(25:15)**
</details>

### Aula #19
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #18 - Parte 1 **(14:26)**
- [ ] **2.** Revisão do desafio da semana #18 - parte 2 **(10:09)**
- [ ] **3.** Revisão do desafio da semana #18 - parte 3 **(14:00)**
- [ ] **4.** Conhecendo outros símbolos usados na Regex **(23:27)**
- [ ] **5.** Métodos de string onde podemos usar regex **(06:31)**
- [ ] **6.** O objeto RegExp() **(21:30)**
</details>

### Aula #20
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #19 - Parte 1 **(11:28)**
- [ ] **2.** Revisão do desafio da semana #19 - parte 2 **(24:23)**
- [ ] **3.** Problemas com áudio no próximo video **(03:26)**
- [ ] **4.** JS no browser - Selecionar elementos do DOM **(13:17)**
- [ ] **5.** JS no browser - parte 2 **(13:46)**
- [ ] **6.** JS no browser - parte 3 - Selecionando elementos do DOM **(12:16)**
- [ ] **7.** JS no browser - parte 4 - Formulários e eventos **(15:36)**
</details>

### Aula #21
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #20 - Parte 1 **(10:25)**
- [ ] **2.** Revisão do desafio da semana #20 - parte 2 **(13:09)**
- [ ] **3.** Revisão do desafio da semana #20 - parte 3 **(13:16)**
- [ ] **4.** `sync` vs `async` **(13:08)**
- [ ] **5.** `setTimeout` **(15:23)**
- [ ] **6.** `setTimeout` vs `setInterval` **(17:26)**
</details>

### Aula #22
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #21 - Parte 1 **(10:55)**
- [ ] **2.** Revisão do desafio da semana #21 - parte 2 **(12:13)**
- [ ] **3.** Propriedades e métodos de funções - parte 1 **(11:35)**
- [ ] **4.** Propriedades e métodos de funções - parte 2 **(09:35)**
- [ ] **5.** Prototype **(12:55)**
- [ ] **6.** Array-like, editorconfig e desafio da semana #22 **(16:09)**
</details>

### Aula #23
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #22 - Parte 1 **(14:06)**
- [ ] **2.** Revisão do desafio da semana #22 - parte 2 **(13:48)**
- [ ] **3.** Debug - parte 1 **(15:11)**
- [ ] **4.** Debug - parte 2 **(10:11)**
- [ ] **5.** Debug - parte 3 **(12:37)**
- [ ] **6.** Debug - parte 4 **(11:18)**
</details>

### Aula #24
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #23 **(12:34)**
- [ ] **2.** Modularização de código - parte 2 **(12:24)**
- [ ] **3.** Modularização de código - parte 3 **(12:47)**
- [ ] **4.** Modularização de código - parte 4 **(15:02)**
- [ ] **5.** Modularização de código - parte 5 **(14:38)**
- [ ] **6.** Modularização de código - parte 6 **(24:51)**
</details>

### Aula #25
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão do desafio da semana #24 - Parte 1 **(12:01)**
- [ ] **2.** Revisão do desafio da semana #24 - parte 2 **(17:03)**
- [ ] **3.** Revisão do desafio da semana #24 - parte 3 **(26:56)**
- [ ] **4.** Scripts e eventos inline **(16:20)**
- [ ] **5.** Eventos **(14:58)**
- [ ] **6.** Mais eventos por elemento **(17:42)**
</details>

### Aula #26
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** O que é DOM e como percorrer os elementos da árvore **(13:58)**
- [ ] **2.** Percorrer DOM - Propriedades - parte 1 **(08:52)**
- [ ] **3.** Percorrer DOM - Propriedades - parte 2 **(10:00)**
- [ ] **4.** Percorrer DOM - Métodos - parte 1 **(11:15)**
- [ ] **5.** Percorrer DOM - Métodos - parte 2 **(06:59)**
- [ ] **6.** Percorrer DOM - Atributos **(08:21)**
</details>

### Aula #27
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio da semana #26 - Parte 1 **(12:32)**
- [ ] **2.** Revisão desafio da semana #26 - Parte 2 **(10:52)**
- [ ] **3.** Revisão desafio da semana #26 - Parte 3 e DOM Fragments **(14:36)**
- [ ] **4.** Eventos **(11:23)**
- [ ] **5.** Técnicas Ninja **(14:00)**
- [ ] **6.** Desafio da semana #27 **(00:58)**
</details>

### Aula #28
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio da semana #27 - Parte 1 **(12:15)**
- [ ] **2.** Revisão desafio da semana #27 - Parte 2 **(15:13)**
- [ ] **3.** Introdução à Ajax **(11:17)**
- [ ] **4.** Ajax - Parte 2 **(10:19)**
- [ ] **5.** Ajax - Parte 3 **(10:42)**
- [ ] **6.** Antes de resolver o desafio 28, por favor, leia! **(00:40)**
- [ ] **7.** Ajax - Parte 4, try/catch e desafio da semana #28 **(10:01)**
</details>

### Aula #29
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio da semana #28 - Parte 1 **(10:22)**
- [ ] **2.** Revisão desafio da semana #28 - Parte 2 **(11:42)**
- [ ] **3.** Revisão desafio da semana #28 - Parte 3 **(15:23)**
- [ ] **4.** Revisão desafio da semana #28 - Parte 4 **(14:21)**
- [ ] **5.** Module Pattern **(15:58)**
- [ ] **6.** Module Pattern - parte 2 e desafio da semana #29 **(07:55)**
</details>

### Aula #30
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Revisão desafio da semana #29 - Parte 1 **(11:17)**
- [ ] **2.** Revisão desafio da semana #29 - Parte 2 **(12:55)**
- [ ] **3.** Revisão desafio da semana #29 - Parte 3 **(16:43)**
- [ ] **4.** Revisão desafio da semana #29 - Parte 4 **(18:15)**
- [ ] **5.** Revisão desafio da semana #29 - Parte 5 **(16:44)**
- [ ] **6.** Module Pattern - closure e desafio #30 **(20:10)**
</details>

### Aula #31
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** DOM - innerHTML **(11:46)**
- [ ] **2.** DOM - innerHTML - Problemas de segurança **(13:09)**
- [ ] **3.** DOM - insertAdjacentHTML **(09:06)**
- [ ] **4.** O objeto Date **(13:35)**
- [ ] **5.** O objeto Date - Propriedades e métodos **(10:28)**
- [ ] **6.** Conhecendo o objeto Math **(11:07)**
</details>

### Aula #32
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Ajax **(11:00)**
- [ ] **2.** REST Api **(14:23)**
- [ ] **3.** REST Api - Cors **(14:49)**
- [ ] **4.** Ajax - sync - POST **(13:24)**
- [ ] **5.** Ajax - POST - Parte 2 **(19:06)**
- [ ] **6.** Ajax - POST - Parte 3 **(08:29)**
</details>

### Aula #33
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Testes **(10:59)**
- [ ] **2.** Escrevendo os primeiros testes **(12:08)**
- [ ] **3.** Entendendo o escopo Red - Green - Blue **(11:37)**
- [ ] **4.** Escrevendo mais testes **(12:57)**
- [ ] **5.** TDD Style **(13:09)**
- [ ] **6.** Documentação do Mocha e Code Coverage **(20:03)**
</details>

### Aula #34
<details>
  <summary>Conteúdo</summary>
<p>

- [ ] **1.** Introdução **(08:41)**
- [ ] **2.** Uglify.js - parte 1 **(13:06)**
- [ ] **3.** Uglify.js - parte 2 **(14:45)**
- [ ] **4.** Sourcemaps **(15:48)**
- [ ] **5.** Diferenças entre console.log e return **(08:48)**
- [ ] **6.** Objetos e encerramento **(24:04)**
</details>

---

- [Deprecated Methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features)
- [UglifyJS](https://www.npmjs.com/package/uglify-js)
- [ESLint](http://eslint.org)
- [JSCS](http://jscs.info)
- [JSHint](http://jshint.com)
- [JSLint](http://jslint.com)
- [StandardJS](https://github.com/feross/standard)
- [SemiStandardJS](https://github.com/Flet/semistandard)
